### ISSUE TITLE
How to reimplement "Focus" feature for custom branches?

### ISSUE THREAD

**Issue by kkneip** [walkinside/sdk#11]
I needed to create an additional FRT like structure (VRBranchKind.Frt + 1) to fullfill our customer's needs. 
A plugin renders this structure in a TreeView. Now I'd like to implement the "Focus" feature via a context menu, but I don't know how to this in detail by using Walkinside's API. (I do not need any help regarding the context menu - only how to adjust the camera to make it behave like the CAD structure.

Best regards,

Karsten

**Comment by griemens** [comment]
Hi Karsten,

Think in your case it is the best to use the IVRObjectBuilder interface.
Basically this allows you to group 3D elements together using the IVRBranch objects. On this group you can then apply actions like set color, set blinking style and jump the camera in front of it.

So you would have
`class MyTreeView
{
    ...
    IVRGroupBuilder m_SelectionGroup = null;
    ....

    // call this with a collection of branches to apply selection behaviour
    void VizualiseSelection(IEnumerable<IVRBranch> branches)
    {
            if (m_SelectionGroup == null)
            {
                m_SelectionGroup = SDKViewer.GroupManager.CreateEmptyGroup();
            }
            m_SelectionGroup.Clear();
           foreach (var branch in branches)
           {
                m_SelectionGroup.Add(branch);
           }

            m_SelectionGroup.ApplyColor(Color.LightGreen);
            m_SelectionGroup.ApplyStyle(VRStyle.Blinking);
            m_SelectionGroup.JumpTo();
    }

}`

If it was CAD and FRT it would have been easier just call IVRBranch.SelectAndFlyTo.
But I gave it a quick try, and it throws exceptions when the branch is not CAD or FRT.

Bye bye

**Comment by kveretennicov** [comment]
@kkneip, you can indeed use `IVRGroupBuilder`/`IVRGroup` as  @griemens suggested.

Note that `IVRGroup.JumpTo` will instantly move Walkinside camera to the target. If you want the same smooth zoom-in effect like in Walkinside Viewer's "Focus", this is how it is achieved:

```c#
var box = selectionGroup.BoundingBox; // or from branch.AABB or constructed in some other way
var radius = box.DiagonalDistance * 0.875; // this is what Viewer does, you can calculate differently if you wish
viewer.Camera.GoTo(box.Center, radius, 0);
```

Don't forget to switch off collision and gravity before `GoTo`:

```c#
viewer.Settings.Collision.Value = false; // also switches off Gravity
```

Does this answer your question?

**Comment by kveretennicov** [comment]
If needed, feel free to open another issue or reopen this one.
