### ISSUE TITLE
Update V7 source code to V10.2SP1

### ISSUE THREAD

**Issue by makiko-SYSPRO** [walkinside/sdk#16]
One of our End-user who started to code COMOS WI V7 SDK and now they need to upgrade it to V10.2SP1 due to implementing PointClouds. When they replace WalkinsideSDK2.dll of V10.2SP1, they found some class ( or code? ) is not applicable due to definition changed from V7 to V10.2.
For example, "SDKViewer.Settings.Navigation.CameraDistance" , system said it's old type. 
However, I could compile with that source code, and DLL worked. 
It was just "warning", but would like to know how to update and rewrite the code for future development. 

I attached build report from Visual studio, it's mixed both EN and JP.
I Hope it still helpful.

[Compile_Report.txt](https://github.com/walkinside/sdk/files/698621/Compile_Report.txt)

**Comment by kveretennicov** [comment]
Thank you, @makiko-syspro, the file you attached was very helpful.

First thing, these are indeed just warnings and these deprecated APIs will continue to work at least until Walkinside 10.3, which is unlikely to be released before 2018 (see our [API Compatibility Policy](https://walkinside.github.io/sdk/docs/html/policy.html) for more details).

Still, it's good to take action in advance and try to fix some of these warnings before they become errors.

I see basically 3 warnings in the log:

1. `VRNavigationSettings.ThirdPerson`

    This is easy to fix, just use `SDKViewer.Settings.ThirdPerson.Value`.

2. `VRNavigationSettings.CameraDistance`

    This setting we planned to eventually make internal, but only because we were not aware of it being used by some plug-ins. If you would explain how your plug-in uses it and what it tries to achieve - we will try to find a good solution.

3. `IVRProject.VolumeManager` and `VRAbstractVolume`

    This is a more interesting case. We would like to eventually remove these APIs. We understand the general usefulness of volumes, but we are not satisfied with volume APIs in their current form. Like the warning message said, it may be possible to cover your case using other existing APIs. Here we again need to understand well your use case, what the plug-in achieves with volumes and how it uses old VolumeManager for that. Then we will come up with a solution.

CC @walkinside/devs

**Comment by kveretennicov** [comment]
@makiko-syspro, any updates from your side on this one?

**Comment by makiko-SYSPRO** [comment]
Sorry for not reply long time !!!

Q1 -> VRNavigationSettings.TrirdPerson
OK, understand.

Q2.  -> Why VRNavigationSettings.CameraDistance is used
Our user wants to pop-up message or warining when camera close to the target position. I asked Andoni (product manager of COMOS WI) to create sample code with V7 as my programming skill is very poor. Please find attached file I sent to him, its describing what our user wanted to do.


Q3. -> IVRProject.VolumeManager and VRAbstractVolume
Same as Q2, our user want to visualize the boundary if camera (or avatar) is outside or inside of the specific area. consequently, if camera is in, they want to execute their own system on top of WI, then operator will study with it. When study finished, it closed and back to WI.

I attached two files describing what this user requested. 
1) 20160715_OMEGA_SDK.xlsx  
   -> Initial request
2) 20160720_OMEGA_SDK_Enhancement.pdf
   -> Enhancement requests

Background of this example code is that our user has their own "Training system of Plant Operation" and they are challenging to implement WI as 3D visualization. Additional unique challenge for this user is implementing "Point Cloud" model so that they can eliminate the cost of As Build 3D model.

Hope my explanation is clear , , ,.

Regards,

Makiko

[20160715_OMEGA_SDK.xlsx](https://github.com/walkinside/sdk/files/732022/20160715_OMEGA_SDK.xlsx)
[20160720_OMEGA_SDK_Enhancement.pdf](https://github.com/walkinside/sdk/files/732035/20160720_OMEGA_SDK_Enhancement.pdf)

**Comment by kveretennicov** [comment]
Thank you, @makiko-syspro. Yes, I work with Andoni - he is known as [@andongro](https://github.com/andgonro) here :) I will check if he has anything to add.

Are you familiar with Proximity Zones feature of Walkinside? It is something that can be used in training scenarios and it sounds very much like what you describe: a volume that can be entered and exited. All the main building blocks that we used ourselves to implement Proximity Zones we also made available in the SDK of Walkinside 10.2.

Those new APIs are part of Walkinside Core SDK now. They are not official yet, meaning they may change in future releases (or even disappear if there is no interest). But we hope to polish them with the help of feedback like yours and eventually make them officially supported. Would you be interested to try to rewrite your examples using Core SDK?

CC @walkinside/staff @walkinside/devs

**Comment by andgonro** [comment]
Hi Makiko,

We are going to look into an alternative for the deprecated code that the example uses before it is finally removed.
As soon as we have an alternative we'll let you know. As @kveretennicov mentions there is already an alternative in our non official Core SDK that is available as preview. We'll see how we can polish it to make it official.
CC @walkinside/staff @walkinside/devs

**Comment by kveretennicov** [comment]
Closing this issue for now.
Feel free to reopen it or to open another one. Thank you.
