### ISSUE TITLE
URL Manager - opening a webpage requiring login and password

### ISSUE THREAD

**Issue by griemens** [walkinside/sdk#17]
Hi,

Think I found a bug using the URL manager using an URL that requires user credentials.

When I open an URL in in Internet Explorer 11, the traditional windows dialog pops up requesting for the user name and password. After providing the information all works fine.

When using this URL in Walkinside URL Manager and try to open it by right clicking an element, the internal walkinside browser provides a page saying "401 - Unauthorized: Access is denied due to invalid credentials." and no dialog for credentials is popped up.

Note: I did a test with C# winform and using the WebBrowser control I have the same behaviour as in IE11 and all works fine.

Thanks,

**Comment by kveretennicov** [comment]
@griemens, does it only happen when you use `IVRUrlManager` from your plug-in? Or does it happen also when you use Walkinside Viewer's browser manually? Trying to understand if it's an SDK-specific bug or a more general Walkinside bug.

**Comment by griemens** [comment]
It is a general Walkinside Bug.

Encountered it when using the SDK calling SDKViewer.UI.ShowUrl() with my URL.
So I tried using the standard Walkinside URL Manager Window (not using any SDK code) and added it as a static URL and also encountered the same issue.

Note: For the time being I can work around it by implementing my own site viewer for Walkinside.

**Comment by kveretennicov** [comment]
Thanks. Viewer's URL Manager window also uses `IVRUIManager.ShowUrl`, so, yes, it makes sense you have the same error with it.

Can you please also try the following:
1. In Walkinside Viewer, open "View | Browser".
2. Enter your site's address manually.

Do you still get a 401 error in that scenario?

**Comment by kveretennicov** [comment]
I tried it here and could reproduce 401 error with a website running in IIS with Windows Authentication.

This is a general bug in Walkinside Viewer, not SDK-only bug. As such, we will handle it internally like other product bugs and not here in GitHub.

From our experience, using websites behind Windows Authentication works best when both client and server are in the same Windows Domain (or in domains with trust relationship configured). When that is not possible, there is one workaround: before running Walkinside, login to the protected website in standalone IE and use "Remember credentials" checkbox. This will allow Walkinside browser to use the remembered credentials and avoid 401 error. Other than that, embedding browser component into your plug-in is indeed not too difficult. Let us know if you encounter any issues on that path.

CC @walkinside/devs @walkinside/staff

**Comment by kveretennicov** [comment]
Internal bug reference: 2071796
