### ISSUE TITLE
IndexOutOfBoundsException with IVRBranch.SelectAndFlyTo and standard FRT branches

### ISSUE THREAD

**Issue by kveretennicov** [walkinside/sdk#18]
`IVRBranch.SelectAndFlyTo()` introduced in Viewer SDK for Walkinside 10.2 had a bug where it threw an exception when used with FRT branches. This has been fixed in current 10.2 SP1 beta.

**Comment by kkneip** [comment]
Will this work on all non-CAD branches? Even FRT+x?

**Comment by kveretennicov** [comment]
@kkneip, at the moment - no, it doesn't work with custom FRTs. But it looks like an omission on our part, I would also expect that it works with custom FRTs. I will check and come back.

**Comment by kveretennicov** [comment]
@kkneip, we would like to make it work with custom FRTs. In general, we want to improve support of custom FRTs across entire Viewer SDK API, to bring it on par with CAD and standard FRT.

At this moment we are close to release with 10.2 SP1. As the release is being stabilized, we are not able to introduce this and other changes to SP1. They will be scheduled for later releases.

CC @walkinside/devs @walkinside/staff

**Comment by kveretennicov** [comment]
Closing. Standard FRT is addressed, custom FRTswill be addressed separately.
