### ISSUE TITLE
Message/event bus for communcation between Plugins

### ISSUE THREAD

**Issue by kkneip** [walkinside/sdk#21]
Hi,
is there a possibility to send messages between viewer plugins?
E.g. I'd like to inform plugin A and B of an action triggered by plugin C.

**Comment by kveretennicov** [comment]
@kkneip, current Viewer SDK does not provide any facility for plug-ins to communicate with each other. We have no plans to add such facility, at least not until we understand the requirements.

There is some work in progress for issue #6, where - as a side effect almost - two plug-ins will be able to read/write the same setting object and receive `ValueChanged` event notifications on it. This may be used as a sort of communication channel between co-operating plug-ins.

In absence of SDK support, this can be achieved with an assembly shared by co-operating plug-ins. The assembly can expose a static event and a method to fire the event. A plug-in then can subscribe and publish events to other subscribed plug-ins.

I remember @aglaapps also mentioned their interest in inter-plug-in communication in issue #14. Is your use case similar to theirs?

CC @walkinside/devs

**Comment by kveretennicov** [comment]
@kkneip, I assume you went with the shared assembly / static event hub approach.

Feel free to reopen if you'd rather have this supported directly by the Viewer SDK. Thank you.
