### ISSUE TITLE
Each selection changes lead to OnBranchUnselectAll AND SelectionChanged

### ISSUE THREAD

**Issue by kkneip** [walkinside/sdk#22]
Hi,

I need to get aware of any selection changes (both select and unselect).
But even if only selection changes I get an OnBranchUnselectAll event followed by a SelectionChanged event.
Is there a need to raise an OnBranchUnselectAll event even when just selection changed? If yes, it would be helpful to get an additional information that this is just a temporary selection state and will be followed by a SelectionChanged event.

**Comment by kveretennicov** [comment]
@kkneip, I agree that it may not seem very logical to raise `OnBranchUnselectAll` in this situation. But at this point it is not safe for SDK to just change this behavior. However illogical it may look, some SDK client code somewhere may depend on it, perhaps "accidentally". Breaking those clients wouldn't be a good thing.

What we can do is introduce a new event `SelectionCleared` and gradually phase out `OnBranchUnselectAll`. We can give `SelectionCleared` the "right" behavior - it should be raised only as a result of explicit request to clear selection, by SDK client or user action.

We will need to go through Viewer SDK and see which APIs should raise the new event. If you have any considerations - they are welcome, as always.

**Comment by kkneip** [comment]
@kveretennicov, adding a new event would be a valuable solution for my issue.

By now I worked around it by just hooking into context menu's click event on "Unselect All" and ignoring `OnBranchUnselectAll` instead.
