### ISSUE TITLE
Find elements from CAD in the FRT and vice versa

### ISSUE THREAD

**Issue by AgLaApps** [walkinside/sdk#26]
Good morning,

This could be a silly question but how could I find a element that I select in the CAD hierarchy in the FRT.

Right now I have a tree hierarchy in the FRT branch with elements of the model and when one is selected in the FRT it opens a windows form, but instead of selecting it from the FRT we want to select it from the CAD or Model, so then we need to search for that element in the FRT to open the needed windows form.

I need something like branch_FRT.FindElementByID(branch_CAD.ID) and vice versa branch_CAD.FindElementByID(branch_FRT.ID).

Thanks in advance.

**Comment by kveretennicov** [comment]
@aglaapps, it's not silly at all :) In fact, it came up recently, see #20 by @kkneip.

My response there applies to your question too. Methods `IVRBranchManager.GetBranchesFromElement` and `IVRBranchManager.GetElementsFromBranch` are deprecated, but still working, and may work for you as a short-term workaround. Can you try that?

In the longer term we could add a dedicated method `IVRBranch.FindMatchesByElements`, it would be easier to use and would execute faster. If we add it, would you be interested in beta-testing?

**Comment by AgLaApps** [comment]
Good morning,

I will try the methods that you mention, and also I will like to beta-test the FindMatchesByElements.

**Comment by kveretennicov** [comment]
Great, we'll update here as soon as new API is available.

**Comment by AgLaApps** [comment]
Thanks for the help, the IVRBranchManager.GetBranchesFromElement and IVRBranchManager.GetElementsFromBranch work greatfully for what I needed. But now I have a new doubt, I´m changing the name of a FRT but when I do it the displayed name is the old one, so to what function should I call to update the displayed FRT.

**Comment by kveretennicov** [comment]
You mean that you do something like `frtBranch.Name = "new name";` and it still shows the old name in Viewer FRT window? It's not exactly an SDK issue (looks like a Viewer bug) and I don't have a suggestion for workaround. But I will make it known to others; if someone has an idea I'll let you know.

**Comment by AgLaApps** [comment]
Exactly, do something like frtBranch.Name = "new name"; and debugging you can see that the names are changed but the viewer FRT window is not updated but when the viewer is closed and reopened the data display correctly.

**Comment by kveretennicov** [comment]
For the FRT branch renaming, we will track this internally as a Viewer bug. To work around it, the user has to close FRT window and open it again.

Internal bug reference: 2119928

**Comment by gcorvala** [comment]
Marked as duplicated of https://github.com/walkinside/sdk/issues/20
