### ISSUE TITLE
Can I control the time it takes to move the camera from A to B?

### ISSUE THREAD

**Issue by andgonro** [walkinside/sdk#29]
Hi,

I would like to be able to have my camera move automatically from point A to point B in X amount of seconds. I have tried to use SDKViewer.Camera.GoTo (VRVector3D, radius, dt) but the dt doesn't seem to work as expected.
The goal is to have avatars moving around in an automated way; is there a possibility to do this somehow?

**Comment by griemens** [comment]
Hi sorry for the late reply but here is a way to do this.

use as **a** the current camera position

    VRVector3D a = SDKViewer.Camera.Position;

use as b destination 10 meters distance in the direction the camera is looking at.

    VRVector3D b = SDKViewer.Camera.Position.Add(
            SDKViewer.Camera.LookAt.Direction.Scale(
                new VRVector3D(10.0f,10.0f,10.0f)));

as time just use 5 seconds

    double time = 5.0;

Create 2 curves that will contain the positions of the camera over time and the camera view direction over time. To have a better understanding of the concept I suggest you play with "Walkinside Animation manager" for example to make a movie.

    VRCurve<VRVector3D> position = VRCurve<VRVector3D>.CreateCurve("my_movement_curve", SDKViewer.ProjectManager.CurrentProject);
    VRCurve<VRVector3D> viewdirection = VRCurve<VRVector3D>.CreateCurve("my_view_curve", SDKViewer.ProjectManager.CurrentProject);

Add to the curve defining the position the location of a, and as time we use 0 (so must be instant)
To the viewdirection curve we add the view target point b with a time of 1 (meaning the camera will have b as center of screen after 1 second is elapsed)
  
    position.Points.Insert(a, 0);
    viewdirection.Points.Insert(b, 1);

Now we add the final destination point. In the position curve we add b and should arrive at known time.
For the viewdirection curve we can not use b, as position and target view point can not be the same. so we will just the view direction vector of the camera.

    position.Points.Insert(b, time);
    viewdirection.Points.Insert(b.Add(SDKViewer.Camera.LookAt.Direction), time);

Play the created curves

    SDKViewer.ProjectManager.CurrentProject.AnimationManager.PlayCurves<VRVector3D>(position, viewdirection, 0);

**Defined as a function this would be something like**

    void MoveTo(VRVector3D a, VRVector3D b, double time)
    {
      VRCurve<VRVector3D> position = VRCurve<VRVector3D>.CreateCurve("my_movement_curve", SDKViewer.ProjectManager.CurrentProject);
      VRCurve<VRVector3D> viewdirection = VRCurve<VRVector3D>.CreateCurve("my_view_curve", SDKViewer.ProjectManager.CurrentProject);

        position.Points.Insert(a, 0);
        viewdirection.Points.Insert(b, 1); // look in direction of b
        position.Points.Insert(b, time);  
        // note the math in following line is pseudo code. a + b must be written as a.Add(b) etc ...
        viewdirection.Points.Insert(b+(b-a).Normalize); 
        SDKViewer.ProjectManager.CurrentProject.AnimationManager.PlayCurves<VRVector3D>(position, viewdirection, 0);
    }

Hope it still helps.
Kind regards

**Comment by kveretennicov** [comment]
Thank you, @griemens.

@andgonro, `Camera.GoTo` indeed works by playing a curve with `AnimationManager.PlayCurves`, so you can mimic and customize its effect using those building blocks.

**Comment by kveretennicov** [comment]
Closing as there is nothing else to add.
