### ISSUE TITLE
COMOS Walkinside V10.2SP1 converters error

### ISSUE THREAD

**Issue by makiko-SYSPRO** [walkinside/sdk#31]
Hello,

I installed official release version of COMOS WI(x86) issue on 2017 Feb 17, then applied translation folder named ja-JP under installed program folder.
I found several comverters were not start up, nor log information.
  1) PDS Converter
  2) JT Converter
  3) SP3D Conveter
  4) Point Could Converter
  
  Only PDMS started up with Japanese interface.
  If I rename ja-JP folder under isntallation program, all converters worked but with English interface.
  
  Please refine all converters to behaive same as PDMS builder.
  
  
  Regards,

SYSPRO CORPORATION  
Makiko YAMADA
  
  
  
![error_msg](https://cloud.githubusercontent.com/assets/25055031/23349201/4dc56b16-fcf4-11e6-9db2-50bfab744a26.png)
[Error_Log.txt](https://github.com/walkinside/sdk/files/802684/Error_Log.txt)

* I tried to attache ja-JP folder by zip file but some how the system didn't accept.
 If you need it, please inviste me to Secure File Exchange or let me know mail address where zip file can be received.

**Comment by kveretennicov** [comment]
Thank you for letting us know.

The translation tool is not part of SDK. To make sure this is handled properly you should report it to GTAC as a general product bug. If you have difficulty reporting through GTAC, I can enter it into our internal bug tracker on your behalf, but then you will not be able to follow its progress.

CC @andongro @griemens

**Comment by makiko-SYSPRO** [comment]
Hello,

OK, thanks.　I have just registered this issue to GTAC with ja-JP 
translation data.
# is 7966416.

Regards,

Makiko YAMADA




送信元: Konstantin Veretennicov <notifications@github.com>
宛先:   walkinside/sdk <sdk@noreply.github.com>
Cc:     makiko-SYSPRO <m_yamada@syspro-net.co.jp>, Author 
<author@noreply.github.com>
日付:   2017/02/27 19:19
件名:   Re: [walkinside/sdk] COMOS Walkinside V10.2SP1 converters error 
(#31)



Thank you for letting us know.
The translation tool is not part of SDK. To make sure this is handled 
properly you should report it to GTAC as a general product bug. If you 
have difficulty reporting through GTAC, I can enter it into our internal 
bug tracker on your behalf, but then you will not be able to follow its 
progress.
CC @andongro @griemens
?

**Comment by kveretennicov** [comment]
Thanks!
I will close this issue then.
