### ISSUE TITLE
Spacial characters in dll file name is ignored in plugins.cfg (COMOS WI V10.2SP1)

### ISSUE THREAD

**Issue by makiko-SYSPRO** [walkinside/sdk#33]
With version 10.2SP1 (COMOS_Walkinside_10.2.33.39.0b), when dll file includes "Space", this plugin dll file is not loaded after restart WI, becaue the space charactor in file name is replaced by "%20".
( Just after turned on the plugin, associated .dll was loaded correctly )
Please see attached file for detail.
This was not happened with V7 (we could use "Space" for dll file name), is there any way to avoid this error ?
![v10_plugin_file](https://cloud.githubusercontent.com/assets/25055031/23543174/5664876e-0034-11e7-8912-c4447bb35662.png)

**Comment by kveretennicov** [comment]
CC @agadoul

**Comment by Agadoul** [comment]
Thanks for reporting this bug. I have found the reason and the fix is currently being reviewed by the team.

**Comment by Agadoul** [comment]
Hi,
I am glad to report that the bug was fixed.
