### ISSUE TITLE
Walkinside SDK Beta Core Preview

### ISSUE THREAD

**Issue by griemens** [walkinside/sdk#35]
Hi,

In the examples collection I can only find 2d examples and a light example.
Will it be possible to draw 3D content using this SDK ?

I would like to render my own waypath for ITS.

A scenario has more then 60 actions and I need to render only the current section of the waypath. Rendering a full way path as walkinside does is not usefull.

Thanks,

**Comment by kveretennicov** [comment]
CC @agadoul @gcorvala @andgonro

**Comment by Agadoul** [comment]
Hi,
Our CoreSdk (Preview) has this feature indeed. It is not yet clean and therefore not all features are easy to use and the Api might change in the next version. So I can try to drive you to create a vbo.

- Create a coreSdk model like desribe in the CountDown example:
https://github.com/walkinside/sdk-beta/blob/master/examples/preview/Core%20SDK/Example%202.%20Countdown/CountdownModel.cs

- overide the method Initialize.

- in the method initiliaze, create VRGenericVertexArray (context.Renderer.MakeGenericVertexArray). The format is an integer, we did not have time to use an enum which would have been easier for developers. Which vertex format do you need? I could tell you which magic integer to use.

- use the context given to subscribe to create a vbo from the generic vertex array.
context.Renderer.MakeVertexBufferObject.

- create a vbo using the vbo in the same manner.

- override render method, bind your vao and call context.Renderer.Draw.

And voila.
I hope this is explained well enough.

I keep in mind to have a Sdk example showing this feature in the close future.
Thanks for your interest and your support,
Axel.

**Comment by griemens** [comment]
Excellent! going to give it a try, and when I have a sample running will upload the code to github.

**Comment by Agadoul** [comment]
magic number should be 18.

**Comment by kveretennicov** [comment]
I assume this has been resolved. Feel free to re-open in case of questions.
