### ISSUE TITLE
IVREntityManager Create method is sequence of results returned defined ?

### ISSUE THREAD

**Issue by griemens** [walkinside/sdk#36]
Hi,

IVREntityManager in Walkinside Viewer SDK has the following method to create entities.
 IEnumerable<IVREntity> Create(IEnumerable<KeyValuePair<string, IDictionary<string, object>>> entityData);

I was wondering if the sequence of entities returned is the same as the sequence the keyvalue pairs are passed as argument.

For example is following code valid 
```
  MyObject[] myobjects = GetAllObjects();
  KeyValuePair<string, IDictionary<string, object>>[] myobjects_values =   GetAllObjectsProperties(myobjects);
  int index = 0;
  foreach(var entity in EntityManager.Create(myobjects_values)
  {
    myobjects[index].Entity = entity;
    index++;
  }
```

The above code is assuming the entities returned is in same order as the myobjects_values passed as argument.

Thank you,

**Comment by kveretennicov** [comment]
Sorry for the delay, the team is quite busy these days.
As far as I can tell - the answer is yes, result order matches input order .

**Comment by kveretennicov** [comment]
We updated SDK documentation for the next package to say that entity creation result order follows input order (like it's done for branch creation).

**Comment by griemens** [comment]
Thats good news, my assumptions were correct.
Thanks
