### ISSUE TITLE
Preview SDK - Edit HseEffects

### ISSUE THREAD

**Issue by Damaso-GaTs** [walkinside/sdk#37]
Hi,

I would like to modify the HSE Effects properties (currentlly a Gas Leak for a presale Demo) but I have been unable to access it with the SDK. The case is that while debugging they are there (see image attached). Am I missing how to access it or is it currently unaccessible? In case I can't do it currently, is there a posibility to release it in a future release version?

![hseeffects](https://user-images.githubusercontent.com/29239147/26872048-792ecb9c-4b75-11e7-984e-804ef6d01b9e.jpg)

**Comment by kveretennicov** [comment]
@Damaso-GaTs, the [`ITS Scenario Manager`](http://sdk.walkinside.com/api-references/viewer-sdk/html/f02f955b-5d71-044a-5374-f600add0f114.htm) does not support HSE manipulation by Viewer SDK clients. As of now, it is purely internal.

We would like to consider this for some future release. Could you please describe the demo that you had in mind? It can be easier for us to make HSE available if we can limit new API to the necessary minimum.

Thank you and apologies for the late reply.

CC @walkinside/devs
