### ISSUE TITLE
Event support for WalkInside components

### ISSUE THREAD

**Issue by PriyankaGR** [walkinside/sdk#38]
Hi,

First of all i wanted to thank you for providing a reusable SDK for WalkInside! 

That said, **I wanted to know if event support like Click, Double click, MouseOut, MouseIn etc for components such as Redlines, Labels are provided**.
Currently i have a requirement to display tool tips on click of a redline and/or label. However, Those objects do not have any event handlers associated with them.

What I noticed when i checked the .NET Inheritance Hierarchy was, The IVRViewerSdk.UI.Control which is the entire 3D Window panel in COMOS Walkinside project is inherited from **System.Windows.UserControl** in .NET. As such, it had so much support for user interaction handling. 
I thought it would be a great idea to make Redlines, Labels etc., could also be made derived from User control or added interaction handling, so that it will provide greater flexibility for the user to customize his application.

Thanks,
Priyanka

**Comment by kveretennicov** [comment]
Thank you for your interest in Walkinside, @PriyankaGR!

It's true that `IVRLabel` (and `IVRRedline`) doesn't have any mouse events. But, as you noticed,   `IVRViewerSdk.UI.Control` has them. If you combine control's mouse events with [`IVRCamera.CastRay`](http://sdk.walkinside.com/api-references/viewer-sdk/html/21c2b429-7b8d-2845-a25a-32cf37912263.htm), you should be able to achieve what you need.

The result of the `IVRCamera.CastRay` has the [`TagID`](http://sdk.walkinside.com/api-references/viewer-sdk/html/54d2a411-54c0-8136-85db-a3977499dc8b.htm) property. If your ray cast hit a redline, it will match some [`IVRRedline.TagID`](http://sdk.walkinside.com/api-references/viewer-sdk/html/1f1b4646-baf1-e6ff-6595-37ba6277e34a.htm).

You can even do ray casts regularly, to know whether there is a label under the mouse pointer (or anything else of interest). In fact, this is basically how Walkinside Viewer's Infotip feature is implemented.

> Currently i have a requirement to display tool tips on click of a redline and/or label.

With the approach I've described above this should be possible: cast ray in control's mouse click handler and if it hits a label/redline - act accordingly. That being said, redlines and labels are already a bit like tooltips, so are you sure you want to add second-degree tooltips?

CC @walkinside/devs

**Comment by PriyankaGR** [comment]
Hi,

Thanks for your quick response!
However I finally found a work-around for my requirement.

What I did was, delete the redlines and select the IVRBranch located at the original redline area and combine the IVRBranch.Selected event with viewer.UI.Control tooltip.

I will definitely try this ICamera.Castray to provide more refined approach to cover the current requirement.

Thanks,
Priyanka GR
