### ISSUE TITLE
Persisting IVRGroup or IVRGroupBuilder

### ISSUE THREAD

**Issue by kkneip** [walkinside/sdk#40]
Hi,

is there a way to persist an instance of <SDK>.GroupManager.CreateEmptyGroup()? I'd like to store a set an IVRGroup in the Model (e.g. via entities) to reuse it in later sessions.

I think recording the order of branches which have been added or removed to the group could solve it, but from my perspective this seems to be an crappy workaround.

Are there any better solutions available?

Best regards,

Karsten

**Comment by kveretennicov** [comment]
Correct, to persist an IVRGroup you need to keep track of the branches that were used to build it and save them somewhere.
