### ISSUE TITLE
Build DLL from Github using CI/CD pipeline ???

### ISSUE THREAD

**Issue by dineshkj** [walkinside/sdk#43]
Hi All,

I would like to get an idea to build dll using CI/CD Pipelines.
Does anyone has an experience? Please give some ideas. 

Cheers, Dinesh

**Comment by kveretennicov** [comment]
@dineshkj, are you asking about specific details of building a Walkinside Viewer SDK plug-in in a CI environment? There isn't anything special about it, if you cn build it locally - you can build it in CI. Just make sure to have good assembly references and output paths. Do you have experience with CI/CD in general?

**Comment by dineshkj** [comment]
@kveretennicov , 
Yes, you right. I need to build plug-in with CI Environment.
Am aware of basic configuration needed for CI/CD pipelines. I did all configuration required for CI/CD.

I can build with powershell using below script,
`"$("<path>\MSBuild.exe") $("Sample\Example1.sln") /t:build /m"`

Same has been used in CI pipeline, which could not detect the path of Walkinside installation with "Just me" mode,
![error1](https://user-images.githubusercontent.com/13269662/38847474-6b426772-421f-11e8-81ad-fbc3c69c7fb9.jpg)

Check the error and found Walkinside installaion path is defined in "SdkExamples.User.Properties.proj" using registry path,
![image](https://user-images.githubusercontent.com/13269662/38847540-ce59e088-421f-11e8-87bb-f40f2dc772d7.png)

Please let me know any other information's required to resolve issue.

Cheers, Dinesh

**Comment by dineshkj** [comment]
@kveretennicov ,

**Comment by dineshkj** [comment]
@kveretennicov ,
I hardcoded Local Walkinside path "C:\Users\<Username>\AppData\Local\Apps\COMOS\COMOS Walkinside 10.2 (64 bit)\" in " SdkExamples.User.Properties.proj"
![image](https://user-images.githubusercontent.com/13269662/38852362-34810c62-4237-11e8-8eed-a217c4ec6298.png)

Its working, Cheers Dinesh

**Comment by kveretennicov** [comment]
@dineshkj, you can also create your own .csproj from scratch, without using `SdkExamples.User.Properties.proj` at all.

Example .csproj and .sln files are tailored to make it easier to run examples out-of-the-box. For actual development it seems better to create your own projects/solutions, which would be tailored to your environment and CI.

**Comment by dineshkj** [comment]
@kveretennicov ,
As you said, am using my own *.csproj & *.sln files. 
I Explained here with Example files. Thanks a lot for support.

Cheers, Dinesh
