### ISSUE TITLE
CAD Search box

### ISSUE THREAD

**Issue by ghost** [walkinside/sdk#44]
Hi,

How to insert text in CAD search text box for searching object using c#?
![cad search box](https://user-images.githubusercontent.com/13269662/40293880-8f1963da-5cf0-11e8-866d-48342ba681e4.JPG)

Thanks

**Comment by kveretennicov** [comment]
Viewer SDK does not provide direct access to this text box (or to this window). There might be another way to achieve what you need, what is it exactly?

**Comment by dkOogway** [comment]
Idea is to search branch without manually enter value in CAD search option. Example., Insert the value using the code (i.e., Another application or browser)

**Comment by dkOogway** [comment]
Hi, we could use the below one to search the object in Walkinside project.

```
var branches = viewer.ProjectManager.CurrentProject.BranchManager.GetBranchesByNameFragmentAndKind(KKSInput, VRBranchKind.Cad);
            if (branches.Count() != 0)
            {
                foreach (IVRBranch branch in branches)
                {
                    string branchName = branch.Name.Replace("/", "");
                    if (branchName == KKSInput)
                    {
                        //Object could be searched
                    }
                    branchVal = branchVal + 1;
                }
            }
```

Thanks Dinesh

**Comment by dkOogway** [comment]
Please close this issue. Thanks
