### ISSUE TITLE
Branch Select is not working

### ISSUE THREAD

**Issue by ghost** [walkinside/sdk#45]
Hi,

I can retrieve list of branch using below code,
```c#
var branches = SDKViewer.ProjectManager.CurrentProject.BranchManager.GetBranchesByNameFragmentAndKind("branchName", VRBranchKind.Cad);
            MessageBox.Show(branches.Count().ToString());
```
Output,
![image](https://user-images.githubusercontent.com/13269662/40526814-92606b6a-6006-11e8-8df7-7acdd2a82320.png)

But i couldn't select the defined branch in CAD hierachy with below,
```c#
var branches = SDKViewer.ProjectManager.CurrentProject.BranchManager.GetBranchesByNameFragmentAndKind(Input, VRBranchKind.Cad);
            foreach (IVRBranch branch in branches)
            {
                branch.Select();
            }
```
Error,
![image](https://user-images.githubusercontent.com/13269662/40526947-53c8103c-6007-11e8-8cf4-ead0013752fa.png)

Could anyone please tell how to select the branch?

Thanks,

**Comment by dkNinety** [comment]
It will work with,
`branch.Select(1);`

But this is obsolete now.

**Comment by kveretennicov** [comment]
First of all, is there some reason why you call `branch.Select()` in a loop? You will not see intermediate results anyway - all you will see is the last branch selected.

Anyway, I tried to reproduce the issue you report using SDK package from https://github.com/walkinside/sdk/releases/tag/from-10.2.35. I used [Example 3](https://github.com/walkinside/sdk/tree/from-10.2.35/examples/official/Viewer%20SDK/Ex3.Form) and added the following lines to the [form's constructor](https://github.com/walkinside/sdk/blob/d7b88ee116eeb4136e53ab08e0198611a563575c/examples/official/Viewer%20SDK/Ex3.Form/MyForm.cs#L25):

```c#
var branches = SDKViewer.ProjectManager.CurrentProject.BranchManager
    .GetBranchesByNameFragmentAndKind("BASE_SLAB", VRBranchKind.Cad);
foreach (IVRBranch branch in branches)
{
    branch.Select();
}
```

I ran it on example Stabilizer project from the Walkinside package. There were no errors.

I suspect some important details are missing from your report, like the fact that you use threads or background workers.

Could you take "Example 3" and modify it until you reproduce the issue in example Stabilizer project, then share those changes with us?

**Comment by dkOogway** [comment]
Reason behind of calling `branch.Select()` in loop is, defined or required value to be searched. Not to get list of values.

Is different from version to version? am using COMOS Walkinside 10.2.34.46.

Will check with Example 3 as suggested and update.

**Comment by kveretennicov** [comment]
Thank you. Once we have the complete minimal code and data to trigger this error, we can debug the issue much faster.

**Comment by dkOogway** [comment]
Good to hear, :)

**Comment by gcorvala** [comment]
Hi @dkOogway, another way that might be good for your use case is using IVRGroupExtensions.Highlight() helper. This will apply style and color to a group of branches but won't trigger selection events. We are closing the issue but feel free to reopen it if it doesn't fit your needs.
