### ISSUE TITLE
HTTP Server

### ISSUE THREAD

**Issue by dkOogway** [walkinside/sdk#49]
Hi,
Use of http server in Walkinside can access 3D object only using localhost, I couldn't use IP or hostname of Machine.
Is this the product default behavior? 

-- Thanks

**Comment by dkOogway** [comment]
Hi, i found this SDK [http://sdk.walkinside.com/api-references/viewer-sdk/html/5485198b-2178-9d73-8c09-85dd427cb832.htm](url)
In properties, there is only option to get the port. How could i access the IP?
--Thanks

**Comment by griemens** [comment]
Hi dkOogway,

Not sure If I understand the question in relation to use IP or Hostname.
The HTTPServer in Walkinside starts listening to the port where walkinside is running.
Normally this should be accessible from external machines using the IP or machine name. But it could be that Windows firewall is blocking incoming requests. Did you verify if firewall allows incoming requests on the defined port ?

To get an IP address of your machine you could Walkinside SDK
   SDKViewer.Networking.MyIP

Or use standard C# code
```
       string host = System.Net.Dns.GetHostName();
       var hostentry = System.Net.Dns.GetHostEntry(host);
       var ipaddresses = hostentry.AddressList.Where(x => x.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork).ToArray();
```

Hope this helps,
Kind regards

**Comment by dkOogway** [comment]
Hi griemens,

Thank you for your support. Yes it helps me to understand.

To test the port access,  I checked in command prompt with below command, port can be accessed in my machine (Windows OS).
telnet "IP_Address" "port_No"

From the above testing, firewall setting is not blocking in my machine. But still i couldn't access the Walkinside HTTP server with IP address which is running inside the Application.

Basically, idea is to access the 3D object using URL using HTTP server, below one is about configuration
![image](https://user-images.githubusercontent.com/39617362/43519436-beef17bc-958f-11e8-8dd6-83c5713af40c.png)

Instead of IP Address, if i use "localhost". I can access the function which navigate to 3D object inside Application.
Ex., http://localhost:5050/VRCadHierarchySearch?Name="Object_Name"

In case you have idea to access using HTTP server using IP. Please share.
Script & idea you provide is very useful.
If i couldn't access with script, i will approach you again. Thanks

**Comment by dkOogway** [comment]
Thanks Andoni,
Solution: Creation of separate proxy server plugin for Walkinside
![image](https://user-images.githubusercontent.com/39617362/44211648-c4313f80-a169-11e8-99fc-d17df3b24af1.png)

Steps about function,
* Access the IP and pass the URL to browser
* Convert IP to localhost
* Default HTTP server in Walkinside will navigate to 3D Object

--
Kind Regards,
