### ISSUE TITLE
How to access the label which was already configured on 3D object?

### ISSUE THREAD

**Issue by dkOogway** [walkinside/sdk#51]
Hi, How to access the label which is already configured on 3D object with context menu 1?
Which means get the same label ID details by click on context menu2.

![image](https://user-images.githubusercontent.com/39617362/44664540-d76ac780-aa13-11e8-9471-d685c7e55912.png)

Right click on label to get the details of corresponding configuration. Please let me know about possibilities.
Thanks

**Comment by griemens** [comment]
Hi dkOogway

Would realy have a closer look at example 7 of SDK examples.
This shows how to create new labels when right clicking in the model, and deleting labels when user righ clicked on one of the labels. Even how to change colors.

So most modules that uses labels do the following

1. Create a label group
2. Create labels based on stored information or defined by user
       a. Evry time when a label is created store it in your dictionary 
>               Dictionary<uint,IVRLabel> myLabels
3 When user clicks on a label (context menu, right click mouse) use the raycast result to detect what label is clicked.
```
       // Get the click information from the Tag property as a VRRaycastResult type.
      VRRayCastResult res = SDKViewer.UI.Control.ContextMenuStrip.Tag as VRRayCastResult;
      IVRLabel label = null;
      if (myLabels.TryGetValue(res.TagID, out label))
      {
             /// Do something with the label
      }
     else
     {
          // Not a label clicked we own. 
     }
```
Note: In case you want to implement your own mouse click you could use also
VRRayCastResult res = SDKViewer.Camera.CastRay(pixel_2d_location)

Hope this helps.

Kind regards

**Comment by dkOogway** [comment]
Hi, Above one is very useful. Thank you so much.
But i could not access the label group created by other context menu. 
But this issue is same as below issue, 
[Issue 50](https://github.com/walkinside/sdk/issues/50)

So i close this issue, Thanks
