### ISSUE TITLE
Get projects from Multiple opened application

### ISSUE THREAD

**Issue by dkOogway** [walkinside/sdk#54]
Hi,
Is there a way to get the projects which is opened in different sessions (Means opened in more than one Walkinside application)?

If i use IVRViewerSdk, only one could be accessed. Is it possible?
Thanks in Advance.

**Comment by griemens** [comment]
The Walkinside SDK instance is per process, and as such the SDK Viewer does not have any information of other walkinside processes running on same machine.

Could you elaborate a bit what is the actual problem you are trying to solve ? Do you have access to a Walkinside server, or are the 3D models only from disk.

Kind regards.

**Comment by dkOogway** [comment]
Hello Griemens,
Am using the 3D models only from disk.
Its not a problem, but i want to know that SDK Viewer could support other process as well. But from your explanation i understood. Thank you so much.

Is there an any other API which is Walkinside application could support this? 

Actually, concept is that... I have created a proxy server separately for Walkinside to access the 3D object from outside even though multiple sessions opened with different project in a machine. Almost i find the solutions. Thanks for your support

Kind Regards, Dinesh
