### ISSUE TITLE
'DockAreas' not founded

### ISSUE THREAD

**Issue by AgLaApps** [walkinside/sdk#58]
Hi, 

When copying the code from your example I get the error shown in the second image. How could I solve it?

Your code:
![Issues](https://user-images.githubusercontent.com/23332129/60820117-1673b880-a1a1-11e9-80f8-c213ca6cc1c7.JPG)

My code:
![Codigo](https://user-images.githubusercontent.com/23332129/60820349-90a43d00-a1a1-11e9-94fe-30d1c8b83730.JPG)

Thank you in advance.

**Comment by griemens** [comment]
Howdie,

Could you verify if your class LoadForm is a subclass from VRForm.
Suspect you have declared your Form something as "internal class LoadForm: Form"
In this case you LoadForm will not have any docking capabilities in Walkinside, and as such the docking properties used in some examples are not available. If docking is not desired the line can be deleted from the code. 

Note : The library WeifenLuo.WinFormsUI.Docking.dll must be referenced as well in your project if the class inherits from VRForm.

**Comment by AgLaApps** [comment]
Hi again, 

I verified what you said and you were right, my Form was not a subclass from VRForm.

I corrected that but now I cannot open the Designer.

This is the Form1 : Form
![image](https://user-images.githubusercontent.com/23332129/60825238-88e99600-a1ab-11e9-8a1c-17d277980e20.png)

Here you can see that i changed to Form1 : VRForm, added 'ussing vrcontext.walkinside.sdk and referenced WeifenLuo.WinFormsUI.Docking
![image](https://user-images.githubusercontent.com/23332129/60825765-bc78f000-a1ac-11e9-8172-5882c415adf7.png)

But even after doing that I cannot see the designer.
![image](https://user-images.githubusercontent.com/23332129/60825841-de727280-a1ac-11e9-912f-6db6c3dccb07.png)

It says that the main/base class 'vrcontext.walkinside.sdk' could not be loaded.

Thank you again in advance.

**Comment by griemens** [comment]
Failure of the designer is a known issue, when referencing 64bits assembly WalkinsideSDK.dll that implements the VRForm.
See [https://github.com/walkinside/sdk/issues/57](https://github.com/walkinside/sdk/issues/57) for a workaround.
