### ISSUE TITLE
Error opening OPC plugin 

### ISSUE THREAD

**Issue by almajidi** [walkinside/sdk#61]
These issues occur in COMOS Walkinside 10.3 (32 bit)

1. I was trying to connect to an OPC server. After i click the connect icon, Walkinside took some time before showing an error message as i provided below. NetApi Error = 0x180. I have try decompile the code and read through it but i can't find what does that "0x180" mean.
 
2. Another time it manage to proceed to the next windows which shows some configuration setting. But when i try to change the server name, an error message pop out stating about "OpcRcw.Comn". What is that file and where may i get it? Does it need to be registered in the System32 of my machine? 

![OPC plugin error](https://user-images.githubusercontent.com/32501672/61194222-c346bc00-a6f2-11e9-8558-8ba51acc5eab.PNG)
![error message on choosing server](https://user-images.githubusercontent.com/32501672/61194230-cd68ba80-a6f2-11e9-8974-21254a211dd9.PNG)

**Comment by andgonro** [comment]
Hi almajidi,

Did you install the OPC Core Components from OPC foundation?
As this is not an API topic can you close this and send the support question by email, please?

**Comment by almajidi** [comment]
Hello andgoro,

I did installed that. 
Noted on that, which email address should i contact to?

**Comment by andgonro** [comment]
You should contact our support through GTAC
https://www.plm.automation.siemens.com/global/en/support/
