### ISSUE TITLE
Change Gravity and Collision

### ISSUE THREAD

**Issue by AgLaApps** [walkinside/sdk#68]
Hi,

I am trying to change gravity and collision and lock them until user does something. I found pViewer.Settings.Gravity and pViewer.Settings.Collision but they dont have Setters implemented.
Is there any way to do it?

Thanks in advance.

**Comment by griemens** [comment]
Howdie,

pViewer.Settings.Gravity an Collision return a value of type IVRSetting<bool>.
This is a kind of Notifyable object.

For your case you can use
  pViewer.Settings.Gravity.Value = False
  pViewer.Settings.Collision.Value = False
