### ISSUE TITLE
Can I get the branches by Attribute through the DataSDK

### ISSUE THREAD

**Issue by andgonro** [walkinside/sdk#9]
I would like to get the branches by Attribute on the Data SDK, is this possible?

Something like
string attribute_name = MyAttributeName;
string attribute_value = MyAttributeValue;
IEnumerable<IBranch> branches_found = project.branches.GetByAttribute(attribute_name,attribute_value);

A more advanced option would be to be able to get all the Branches that match several attribute values for the same attribute name.

string attribute_name = MyAttributeName;
List<string> attribute_values = new List<string>();
attribute_values.Add("attribute_value1");
attribute_values.Add("attribute_value2");
attribute_values.Add("attribute_value3");
IEnumerable<IBranch> branches_found = project.branches.GetByAttribute(attribute_name,attribute_values);

this would return all the branches that match any of the attribute_values give.

**Comment by kveretennicov** [comment]
@andgonro, there is no such API in current Data SDK.

Can you illustrate this with more details about the use case? The API you propose makes sense, but it's possible that in the context of the use case we can find a better or more efficient solution.

CC @walkinside/devs

**Comment by Agadoul** [comment]
@andgonro Thanks for your feedback. This can be achieved via Lynq queries:

```
 IProjectAttributeSource pdmsAttributeSource = project.AttributeSources.GetAll()
                    .Single(attrSrc => attrSrc.Kind.Equals(ProjectAttributeSourceKinds.Pdms));

var attributeKey = pdmsAttributeSource.CreateKey("Type:=");
var foundBranches = pdmsAttributeSource.GetAll() // get all attributes of all branches
 .Where(a => a.Key == attributeKey && ((int)a.Value) == 5 )
                    .Select(a => a.Branch);
```

Is that what you would like to achieve or is there something i misunderstood?

**Comment by kveretennicov** [comment]
I think the problem with `GetAll().Where` is that it's too slow beyond small attribute databases. We need specific `GetBy...()` filtering methods to take performance advantage of indexing and other techniques close to data source.

**Comment by gcorvala** [comment]
Dear @andgonro, as a workaround was provided, we close the issue. Feel free to reopen if performance is a problem.
